name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - shell: bash
      run: |
        ls
        pwd
    - name: Build the Docker image
      run: docker build ./dockerpro/Dockerfile --tag my-image-name:$(date +%s) 
